version: "3.7"
services:
  api:
    build:
      context: ./PetrolPricesApi
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
    volumes:
      - ./PetrolPricesApi:/var/www
    networks:
      - lahmi
    ports:
      - 8080:8080

  client:
    build:
      context: ./PetrolPricesClient
    working_dir: /app
    depends_on:
      - api
    volumes:
      - ./PetrolPricesClient:/app
    networks:
      - lahmi
    ports:
      - 3000:80

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: user
      MYSQL_USER: pass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - lahmi

  nginx:
    image: nginx:alpine
    ports:
      - 8005:80
    depends_on:
      - db
      - api
      - client
    volumes:
      - ./PetrolPricesApi:/var/www/api
      - ./PetrolPricesClient:/var/www/client
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lahmi

networks:
  lahmi:
    driver: bridge

volumes:
  dbdata:
    driver: local