version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - lahmi

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_USER: 'user'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql





    volumes:
      - dbdata:/var/lib/mysql
      - /docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - /docker-compose/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - lahmi

  nginx:
    image: nginx:alpine
    ports:
      - 8005:80
    depends_on:
      - db
      - app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lahmi

networks:
  lahmi:
    driver: bridge

volumes:
  dbdata:
    driver: local

